# Generated by Django 5.2.11 on 2026-03-17 14:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('mac_adresse', models.CharField(db_index=True, max_length=17, unique=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('firmware', models.CharField(blank=True, max_length=50)),
                ('uptime', models.DurationField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('up', 'Opérationnel'), ('down', 'Hors ligne'), ('maintenance', 'Maintenance')], default='down', max_length=20)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('ram_usage', models.FloatField(default=0.0)),
                ('derniere_vue', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Point d'Accès",
                'verbose_name_plural': "Points d'Accès",
            },
        ),
        migrations.CreateModel(
            name='WifiAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severite', models.CharField(choices=[('low', 'Information'), ('medium', 'Avertissement'), ('high', 'Critique')], default='medium', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('est_resolu', models.BooleanField(default=False)),
                ('access_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='wifi.accesspoint')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WifiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_adresse', models.CharField(db_index=True, max_length=17, unique=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=100)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('snr', models.IntegerField(blank=True, null=True)),
                ('derniere_connexion', models.DateTimeField(auto_now=True)),
                ('access_point_actuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_connectes', to='wifi.accesspoint')),
            ],
        ),
        migrations.CreateModel(
            name='WifiMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('clients_2ghz', models.PositiveIntegerField(default=0)),
                ('clients_5ghz', models.PositiveIntegerField(default=0)),
                ('channel_utilization', models.FloatField(default=0.0)),
                ('traffic_tx_bytes', models.BigIntegerField(default=0)),
                ('traffic_rx_bytes', models.BigIntegerField(default=0)),
                ('access_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='wifi.accesspoint')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['access_point', 'timestamp'], name='wifi_wifime_access__a496cc_idx')],
            },
        ),
    ]
