# Generated by Django 5.2.14 on 2026-06-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wificlient',
            name='est_bloque',
            field=models.BooleanField(default=False, help_text="Client bloqué par l'admin"),
        ),
        migrations.AddField(
            model_name='wificlient',
            name='score_confiance',
            field=models.IntegerField(default=80, help_text='Score de confiance 0-100 (0=dangereux, 100=sûr)'),
        ),
    ]
