# Generated by Django 5.2.10 on 2026-01-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalactivite',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
