# Generated by Django 5.2.10 on 2026-01-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_journalactivite_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
