# Generated by Django 5.2.10 on 2026-01-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profil_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='date_suppression_programmee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='est_gelé',
            field=models.BooleanField(default=False),
        ),
    ]
