# Generated by Django 5.2.11 on 2026-03-07 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0026_equipementreseau_snmp_community_statreseau_anomalies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRemediation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('script', models.TextField(help_text='Commande ou script à exécuter via SSH ou Docker API')),
                ('automatique', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueRemediation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec')], max_length=50)),
                ('sortie_log', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remediation.actionremediation')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.equipementreseau')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.incident')),
            ],
        ),
    ]
