# Generated by Django 5.2.11 on 2026-03-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalieRegle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Processus Zombies', max_length=150, unique=True)),
                ('cmd_detection', models.TextField(help_text='Commande de détection, ex: ps -ef | grep defunct')),
                ('cmd_remediation', models.TextField(help_text='Commandes de remédiation (séparées par des sauts de ligne si plusieurs)')),
                ('os_cible', models.CharField(choices=[('all', 'Tous (Universel)'), ('linux', 'Linux'), ('windows', 'Windows')], default='linux', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
