# Generated by Django 5.2.10 on 2026-01-18 20:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipementReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_equipement', models.CharField(choices=[('routeur', 'Routeur'), ('switch', 'Switch'), ('serveur', 'Serveur'), ('parefeu', 'Pare-feu'), ('autre', 'Autre')], max_length=20)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('port_ssh', models.PositiveIntegerField(default=22)),
                ('utilisateur_ssh', models.CharField(max_length=100)),
                ('mot_de_passe_ssh_chiffre', models.TextField(help_text='Mot de passe SSH chiffré avec Fernet')),
                ('cle_publique', models.TextField(blank=True, help_text='Clé publique SSH si utilisée', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('actif', models.BooleanField(default=True, help_text='Permet de désactiver la supervision de cet équipement')),
                ('derniere_verification', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en ligne', '🟢 En ligne'), ('hors ligne', '🔴 Hors ligne'), ('inconnu', '⚪ Inconnu')], default='inconnu', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Équipement réseau',
                'verbose_name_plural': 'Équipements réseau',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CommandeAutomatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('contenu', models.TextField(help_text='Commandes SSH à exécuter (séparées par des sauts de ligne)')),
                ('confirmation_requise', models.BooleanField(default=True)),
                ('critique', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('applicable_pour', models.ManyToManyField(blank=True, related_name='commandes_applicables', to='monitoring.equipementreseau')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('niveau', models.CharField(choices=[('info', 'Info'), ('avertissement', 'Avertissement'), ('critique', 'Critique')], default='info', max_length=20)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('résolu', 'Résolu')], default='ouvert', max_length=20)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitoring.equipementreseau')),
            ],
        ),
        migrations.CreateModel(
            name='JournalReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('commande_executee', models.TextField(blank=True, null=True)),
                ('resultat', models.CharField(blank=True, max_length=100, null=True)),
                ('sortie_ssh', models.TextField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('ip_utilisateur', models.GenericIPAddressField(blank=True, null=True)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.equipementreseau')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='StatReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ping_ms', models.FloatField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('ram_usage', models.FloatField(blank=True, null=True)),
                ('date_releve', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='monitoring.equipementreseau')),
            ],
            options={
                'ordering': ['-date_releve'],
            },
        ),
    ]
