# Generated by Django 5.2.10 on 2026-01-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipementreseau',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipementreseau',
            name='disk_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipementreseau',
            name='latence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipementreseau',
            name='network_bandwidth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipementreseau',
            name='ram_usage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
