# Generated by Django 5.2.10 on 2026-01-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_equipementreseau_cpu_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipementreseau',
            name='mot_de_passe',
            field=models.CharField(default='sasu', help_text='Mot de passe SSH', max_length=100),
        ),
        migrations.AddField(
            model_name='equipementreseau',
            name='utilisateur',
            field=models.CharField(default='sasu', help_text="Nom d'utilisateur SSH, ex: ubuntu", max_length=50),
        ),
    ]
