# Generated by Django 5.2.10 on 2026-01-19 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_equipementreseau_mot_de_passe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Type d’action (connexion, exécution de commande, etc.)', max_length=255)),
                ('resultat', models.CharField(choices=[('succès', 'Succès'), ('échec', 'Échec'), ('avertissement', 'Avertissement')], default='succès', max_length=20)),
                ('ip_source', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True, help_text='Sortie brute ou erreur SSH.', null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions', to='monitoring.equipementreseau')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de connexion',
                'verbose_name_plural': 'Historiques des connexions',
                'ordering': ['-date_action'],
            },
        ),
    ]
