# Generated by Django 5.2.10 on 2026-01-20 23:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_historiqueconnexion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativeAccesCritique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tentatives', models.PositiveIntegerField(default=0)),
                ('derniere_tentative', models.DateTimeField(default=django.utils.timezone.now)),
                ('bloque_jusqua', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives_critiques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
