# Generated by Django 5.2.10 on 2026-01-22 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_tentativeaccescritique'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('statut', models.CharField(default='en attente', max_length=50)),
                ('resultat', models.JSONField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('date_execution', models.DateTimeField(default=django.utils.timezone.now)),
                ('duree', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_execution'],
            },
        ),
    ]
