# Generated by Django 5.2.10 on 2026-01-25 00:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_tachemonitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='derniere_detection',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='notifie',
            field=models.BooleanField(default=False),
        ),
    ]
