# Generated by Django 5.2.10 on 2026-01-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_incident_derniere_detection_incident_notifie'),
    ]

    operations = [
        migrations.AddField(
            model_name='statreseau',
            name='bandwidth_in_mbps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='bandwidth_out_mbps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='cpu_load_1m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='cpu_load_5m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='disk_read_mb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='disk_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='disk_write_mb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='drops_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='drops_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='errors_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='errors_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='fan_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='health_score',
            field=models.IntegerField(blank=True, help_text='Score global 0–100 calculé', null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='inode_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='jitter_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='packet_loss',
            field=models.FloatField(blank=True, help_text='% de paquets perdus', null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='power_supply_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='ram_total_mb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='ram_used_mb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='temperature_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='statreseau',
            index=models.Index(fields=['equipement', 'date_releve'], name='monitoring__equipem_fb0347_idx'),
        ),
    ]
