# Generated by Django 5.2.10 on 2026-01-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_statreseau_bandwidth_in_mbps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statreseau',
            name='alerte_envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
