# Generated by Django 5.2.10 on 2026-01-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_equipementreseau_echec_consecutif_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statreseau',
            name='health_score',
            field=models.IntegerField(blank=True, default=100, help_text='Score global 0–100 calculé', null=True),
        ),
    ]
