# Generated by Django 5.2.10 on 2026-01-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_alter_statreseau_health_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipementreseau',
            name='alertes_email_active',
            field=models.BooleanField(default=True, help_text="Autoriser l'envoi d'alertes email pour cet équipement"),
        ),
    ]
