# Generated by Django 5.2.10 on 2026-01-28 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_equipementreseau_alertes_email_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_source', models.CharField(max_length=50)),
                ('interface_destination', models.CharField(max_length=50)),
                ('type_lien', models.CharField(choices=[('ethernet', 'Ethernet'), ('fibre', 'Fibre'), ('vpn', 'VPN')], default='ethernet', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_entrants', to='monitoring.equipementreseau')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_sortants', to='monitoring.equipementreseau')),
            ],
        ),
    ]
