# Generated by Django 5.2.10 on 2026-01-29 09:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_lienreseau'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiAccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricant', models.CharField(blank=True, max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('version_firmware', models.CharField(blank=True, max_length=100)),
                ('mode_gestion', models.CharField(choices=[('standalone', 'Standalone'), ('controller', 'Géré par contrôleur'), ('cloud', 'Cloud')], default='standalone', max_length=20)),
                ('adresse_mac', models.CharField(max_length=17, unique=True)),
                ('nb_clients_max', models.PositiveIntegerField(default=50)),
                ('actif', models.BooleanField(default=True)),
                ('dernier_scan', models.DateTimeField(blank=True, null=True)),
                ('equipement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wifi_ap', to='monitoring.equipementreseau')),
            ],
        ),
        migrations.CreateModel(
            name='WifiRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bande', models.CharField(choices=[('2.4', '2.4 GHz'), ('5', '5 GHz'), ('6', '6 GHz')], max_length=10)),
                ('canal', models.PositiveIntegerField()),
                ('largeur_canal_mhz', models.PositiveIntegerField(default=20)),
                ('puissance_tx_dbm', models.IntegerField()),
                ('bruit_dbm', models.IntegerField(blank=True, null=True)),
                ('radio_active', models.BooleanField(default=True)),
                ('taux_utilisation', models.FloatField(blank=True, help_text='Utilisation radio (%)', null=True)),
                ('ap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radios', to='monitoring.wifiaccesspoint')),
            ],
        ),
        migrations.CreateModel(
            name='WifiSSID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('securite', models.CharField(choices=[('open', 'Ouvert'), ('wpa2', 'WPA2-PSK'), ('wpa3', 'WPA3-SAE'), ('enterprise', 'WPA2/WPA3-Enterprise')], max_length=30)),
                ('vlan', models.PositiveIntegerField()),
                ('isolation_clients', models.BooleanField(default=False)),
                ('qos_profile', models.CharField(blank=True, help_text='Profil QoS (VoIP, invité, critique…)', max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('radios', models.ManyToManyField(blank=True, related_name='ssids', to='monitoring.wifiradio')),
            ],
        ),
        migrations.CreateModel(
            name='WifiIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(choices=[('canal_sature', 'Canal saturé'), ('interference', 'Interférence'), ('debit_faible', 'Débit faible'), ('auth_fail', 'Échec authentification'), ('radio_down', 'Radio inactive')], max_length=50)),
                ('description', models.TextField()),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('resolu', models.BooleanField(default=False)),
                ('ap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.wifiaccesspoint')),
                ('radio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.wifiradio')),
                ('ssid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.wifissid')),
            ],
        ),
        migrations.CreateModel(
            name='WifiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fabricant', models.CharField(blank=True, max_length=100)),
                ('type_device', models.CharField(choices=[('pc', 'PC'), ('mobile', 'Mobile'), ('iot', 'IoT'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('rssi', models.IntegerField(help_text='Signal (dBm)')),
                ('snr', models.IntegerField(blank=True, null=True)),
                ('tx_rate_mbps', models.FloatField(blank=True, null=True)),
                ('rx_rate_mbps', models.FloatField(blank=True, null=True)),
                ('roaming', models.BooleanField(default=False)),
                ('connecte_depuis', models.DateTimeField()),
                ('dernier_paquet', models.DateTimeField(blank=True, null=True)),
                ('radio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.wifiradio')),
                ('ssid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.wifissid')),
            ],
        ),
        migrations.CreateModel(
            name='WifiStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_releve', models.DateTimeField(default=django.utils.timezone.now)),
                ('nb_clients', models.PositiveIntegerField()),
                ('debit_total_mbps', models.FloatField()),
                ('taux_erreur', models.FloatField(blank=True, null=True)),
                ('taux_retry', models.FloatField(blank=True, null=True)),
                ('canal_sature', models.BooleanField(default=False)),
                ('ap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.wifiaccesspoint')),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.wifiradio')),
            ],
        ),
    ]
