# Generated by Django 5.2.10 on 2026-01-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_wifiaccesspoint_wifiradio_wifissid_wifiincident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiaccesspoint',
            name='etat',
            field=models.CharField(choices=[('ok', 'OK'), ('alerte', 'Alerte'), ('maintenance', 'Maintenance'), ('offline', 'Hors ligne')], default='ok', max_length=20),
        ),
        migrations.AddField(
            model_name='wificlient',
            name='intrus',
            field=models.BooleanField(default=False, help_text='Client détecté comme suspect'),
        ),
        migrations.AddField(
            model_name='wifiincident',
            name='action_appliquee',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wifiradio',
            name='canal_auto',
            field=models.BooleanField(default=True, help_text='Autoriser le changement automatique de canal'),
        ),
        migrations.AddField(
            model_name='wifissid',
            name='commandes_interdites',
            field=models.JSONField(blank=True, help_text='Actions interdites sur ce SSID', null=True),
        ),
    ]
