# Generated by Django 5.2.10 on 2026-01-30 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_wifiaccesspoint_etat_wificlient_intrus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_recommandation', models.CharField(choices=[('canal', 'Changement de canal'), ('puissance', 'Ajustement puissance'), ('equilibrage', 'Équilibrage clients'), ('securite', 'Sécurité'), ('performance', 'Performance')], max_length=50)),
                ('message', models.TextField()),
                ('gravite', models.IntegerField(default=3, help_text='1=info, 3=important, 5=critique')),
                ('justification', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('appliquee', models.BooleanField(default=False)),
                ('ap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.wifiaccesspoint')),
                ('radio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.wifiradio')),
                ('ssid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.wifissid')),
            ],
        ),
    ]
