# Generated by Django 5.2.10 on 2026-01-31 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_wifirecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePlanifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_execution', models.DateTimeField()),
                ('valide', models.BooleanField(default=False)),
                ('execute', models.BooleanField(default=False)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.commandeautomatique')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.equipementreseau')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_config', models.CharField(choices=[('dhcp', 'DHCP'), ('dns', 'DNS'), ('wifi', 'Wi-Fi'), ('firewall', 'Firewall'), ('vlan', 'VLAN'), ('autre', 'Autre')], max_length=50)),
                ('contenu', models.TextField(help_text='Contenu du fichier de configuration')),
                ('chemin_destination', models.CharField(help_text='Ex: /etc/dhcp/dhcpd.conf', max_length=255)),
                ('redemarrage_service', models.CharField(blank=True, help_text='Service à redémarrer après application', max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='monitoring.equipementreseau')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.TextField()),
                ('succes', models.BooleanField(default=False)),
                ('sortie', models.TextField(blank=True)),
                ('erreur', models.TextField(blank=True)),
                ('date_execution', models.DateTimeField(auto_now_add=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.equipementreseau')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RollbackConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_avant', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.commandeautomatique')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.equipementreseau')),
            ],
        ),
    ]
