# Generated by Django 5.2.10 on 2026-01-31 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_changeplanifie_configurationequipement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeplanifie',
            name='execute',
        ),
        migrations.RemoveField(
            model_name='changeplanifie',
            name='valide',
        ),
        migrations.AddField(
            model_name='changeplanifie',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='changeplanifie',
            name='commentaire_validation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='changeplanifie',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changeplanifie',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changeplanifie',
            name='derniere_execution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changeplanifie',
            name='frequence',
            field=models.CharField(choices=[('once', 'Une fois'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire')], default='once', max_length=20),
        ),
        migrations.AddField(
            model_name='changeplanifie',
            name='statut',
            field=models.CharField(choices=[('en_attente', '⏳ En attente de validation'), ('valide', '✅ Validé'), ('rejete', '❌ Rejeté'), ('execute', '⚙️ Exécuté'), ('annule', '🚫 Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='changeplanifie',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changements_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='changeplanifie',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planifications', to='monitoring.commandeautomatique'),
        ),
        migrations.AlterField(
            model_name='changeplanifie',
            name='equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changements_planifies', to='monitoring.equipementreseau'),
        ),
        migrations.DeleteModel(
            name='RollbackConfig',
        ),
    ]
