# Generated by Django 5.2.10 on 2026-02-04 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_remove_changeplanifie_execute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_racine', models.CharField(max_length=100)),
                ('confiance', models.FloatField(help_text='0.0 → 1.0')),
                ('resume', models.TextField()),
                ('details', models.JSONField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_ia', to='monitoring.incident')),
            ],
        ),
    ]
