# Generated by Django 5.2.10 on 2026-02-04 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_analyseia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRemediationIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.JSONField()),
                ('rollback', models.JSONField()),
                ('risque', models.CharField(max_length=50)),
                ('validation_humaine', models.BooleanField(default=True)),
                ('analyse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoring.analyseia')),
            ],
        ),
    ]
