# Generated by Django 5.2.10 on 2026-02-04 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0020_planremediationia'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='analyse_ia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyseia',
            name='incident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_ia', to='monitoring.incident'),
        ),
    ]
