# Generated by Django 5.2.10 on 2026-02-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_incident_analyse_ia_alter_analyseia_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseia',
            name='analyse_ia_en_cours',
            field=models.BooleanField(default=False),
        ),
    ]
