# Generated by Django 5.2.10 on 2026-02-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_analyseia_analyse_ia_en_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportExecutif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('resume_global', models.TextField()),
                ('analyse_ia', models.TextField()),
                ('nb_incidents', models.PositiveIntegerField(default=0)),
                ('nb_equipements_impactes', models.PositiveIntegerField(default=0)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='analyseia',
            old_name='resume',
            new_name='solution_humaine',
        ),
        migrations.RemoveField(
            model_name='analyseia',
            name='analyse_ia_en_cours',
        ),
        migrations.RemoveField(
            model_name='analyseia',
            name='details',
        ),
        migrations.AddField(
            model_name='analyseia',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analyseia',
            name='explication_simple',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analyseia',
            name='remediation_auto',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='analyseia',
            name='cause_racine',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='analyseia',
            name='confiance',
            field=models.FloatField(),
        ),
    ]
