# Generated by Django 5.2.10 on 2026-02-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0023_rapportexecutif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='analyse_ia',
        ),
        migrations.AddField(
            model_name='incident',
            name='analyse_ia_en_cours',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='analyseia',
            name='incident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_ia', to='monitoring.incident'),
        ),
    ]
