# Generated by Django 5.2.10 on 2026-02-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_remove_incident_analyse_ia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementreseau',
            name='mot_de_passe_ssh_chiffre',
            field=models.TextField(blank=True, help_text='Mot de passe SSH chiffré avec Fernet', null=True),
        ),
    ]
