# Generated by Django 5.2.10 on 2026-02-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0025_alter_equipementreseau_mot_de_passe_ssh_chiffre'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipementreseau',
            name='snmp_community',
            field=models.CharField(blank=True, default='public', help_text='Communauté SNMP (ex: public, private)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statreseau',
            name='anomalies',
            field=models.TextField(blank=True, help_text="Liste des anomalies détectées par l'analyse des logs", null=True),
        ),
    ]
