# Generated by Django 5.2.11 on 2026-03-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0026_equipementreseau_snmp_community_statreseau_anomalies'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeautomatique',
            name='os_cible',
            field=models.CharField(choices=[('all', 'Tous (Universel)'), ('linux', 'Linux Uniquement'), ('windows', 'Windows Uniquement')], default='linux', help_text="Système d'exploitation cible pour cette commande.", max_length=10),
        ),
    ]
