# Generated by Django 5.2.11 on 2026-03-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0027_commandeautomatique_os_cible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementreseau',
            name='type_equipement',
            field=models.CharField(choices=[('routeur', 'Routeur'), ('switch', 'Switch'), ('serveur', 'Serveur Linux'), ('serveur_win', 'Serveur Windows'), ('pc_win', 'PC Windows'), ('parefeu', 'Pare-feu'), ('autre', 'Autre')], max_length=20),
        ),
    ]
