# Generated by Django 5.2.11 on 2026-03-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0028_alter_equipementreseau_type_equipement'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipementreseau',
            name='derniere_alerte_sante',
            field=models.DateTimeField(blank=True, help_text="Date du dernier envoi d'email de santé (pour limitation 2/h)", null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='categorie',
            field=models.CharField(choices=[('sante', 'Santé'), ('securite', 'Sécurité'), ('decouverte', 'Découverte'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='analyse_ia_en_cours',
            field=models.BooleanField(default=False),
        ),
    ]
