# Generated by Django 5.2.11 on 2026-03-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0029_equipementreseau_derniere_alerte_sante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipementreseau',
            name='pos_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipementreseau',
            name='pos_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
