# Generated by Django 5.2.12 on 2026-03-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0030_equipementreseau_pos_x_equipementreseau_pos_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementreseau',
            name='type_equipement',
            field=models.CharField(choices=[('routeur', 'Routeur'), ('switch', 'Switch'), ('serveur', 'Serveur Linux'), ('serveur_win', 'Serveur Windows'), ('pc_win', 'PC Windows'), ('parefeu', 'Pare-feu'), ('wifi', "Point d'accès Wi-Fi"), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipementreseau',
            name='utilisateur_ssh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
