# Generated by Django 5.2.10 on 2026-02-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecouverteReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField(unique=True)),
                ('adresse_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('fabricant', models.CharField(blank=True, max_length=255, null=True)),
                ('deja_connu', models.BooleanField(default=False)),
                ('valide', models.BooleanField(default=False)),
                ('detecte_le', models.DateTimeField(auto_now_add=True)),
                ('dernier_scan', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReseauScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cidr', models.CharField(max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('dernier_scan', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
