# Generated by Django 5.2.10 on 2026-02-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipementDecouvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('type_detecte', models.CharField(default='inconnu', max_length=50)),
                ('vu_le', models.DateTimeField(auto_now=True)),
                ('ajoute', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='DecouverteReseau',
        ),
        migrations.DeleteModel(
            name='ReseauScan',
        ),
    ]
