# Generated by Django 5.2.10 on 2026-02-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_equipementdecouvert_delete_decouvertereseau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipementdecouvert',
            name='email_envoye',
            field=models.BooleanField(default=False),
        ),
    ]
