# Generated by Django 5.2.10 on 2026-02-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_equipementdecouvert_email_envoye'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipementdecouvert',
            name='mac_addresse',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='equipementdecouvert',
            name='systeme_exploitation',
            field=models.CharField(default='inconue', max_length=50),
        ),
    ]
