"""
Django settings for InfraContol project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""

import os
from pathlib import Path
from ssl import CERT_NONE
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
SECRET_KEY = env('SECRET_KEY', default='django-insecure-fallback-key')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'crispy_forms',
    'crispy_bootstrap5',
    'core',
    'automation',
    'discovery',
    'monitoring',
    'wifi',
    'aiengine',
    'reports',
    'training',
    'notifications',
    'remediation',
    'channels',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'django_prometheus',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'core.middleware.BotDefenseMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.CompteGeleMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'InfraContol.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'monitoring.context_processors.maintenance_globale',
            ],
        },
    },
]

WSGI_APPLICATION = 'InfraContol.wsgi.application'
ASGI_APPLICATION = 'InfraContol.asgi.application'

# Database
DATABASES = {
    'default': env.db(),
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Douala'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redis & Caching
REDIS_URL = env('REDIS_URL', default='redis://localhost:6379/1')

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_RESULT_EXPIRES = 3600
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "visibility_timeout": 3600,
    "ssl": { "ssl_cert_reqs": CERT_NONE } if REDIS_URL.startswith('rediss') else {}
}

from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    "purge-anciens-logs": {
        "task": "core.tasks.purge_old_logs",
        "schedule": crontab(hour=2, minute=0),
    },
    "purge-comptes-supprimes": {
        "task": "core.tasks.purge_comptes_supprimes",
        "schedule": crontab(hour=3, minute=0),
    },
    "verifier-equipements-toutes-les-5-min": {
        "task": "monitoring.tasks.verifier_statut_equipements",
        "schedule": crontab(minute='*/5'),
    },
    "analyse-anomalies-toutes-5-min": {
        "task": "monitoring.tasks.tache_analyse_anomalies",
        "schedule": 300.0,
    },
    "collecter-stats": {
        "task": "monitoring.tasks.collecter_toutes_les_stats",
        "schedule": 60,
    },
    "ia-incidents-critiques": {
        "task": "aiengine.tasks.analyser_incidents_critiques",
        "schedule": 300,
    },
    "ia-incidents-recurrents": {
        "task": "aiengine.tasks.analyser_incidents_recurrents",
        "schedule": crontab(minute=0),
    },
    "rapport-executif": {
        "task": "reports.tasks.generer_rapport_hebdomadaire",
        "schedule": crontab(day_of_week="mon", hour=8, minute=0),
    },
    "wifi-collect": {
        "task": "wifi.tasks.collecter_wifi_all",
        "schedule": 600.0,
    },
    "discovery-scan-auto": {
        "task": "discovery.tasks.scanner_reseau_auto",
        "schedule": crontab(minute=0, hour="*/2"),
    },
    "envoi-resume-alertes": {
        "task": "monitoring.tasks.envoi_resume_quotidien",
        "schedule": crontab(minute="*/15"),
    },
}

# Channel Layers
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# OTP (2FA)
OTP_TOTP_TOLERANCE = 6
OTP_TOTP_DIGITS = 6
OTP_TOTP_STEP = 30

# Authentication
LOGIN_URL = "/connexion/"
LOGIN_REDIRECT_URL = "/dashboard/"
MAX_FAILED_ATTEMPTS = 5
BLOCK_TIME_MINUTES = 10

# Security
from cryptography.fernet import Fernet
FERNET_KEY = env('FERNET_KEY', default='h8zJPcRRkl68FuIoPsWOwqwIDbehMbtrH-La5GtFgv0=')

# Logging
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] [{levelname}] {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOGS_DIR, "monitoring.log"),
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "monitoring": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": True,
        },
        "ai": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}

# Email (Brevo)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp-relay.brevo.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=2525)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='admin@infracontrol.local')
ADMIN_EMAILS = env.list('ADMIN_EMAILS', default=[])

# Ollama IA
OLLAMA_URL = env('OLLAMA_URL', default='http://localhost:11434')

# Groq IA
GROQ_API_KEY = env('GROQ_API_KEY', default=None)
GROQ_MODEL = env('GROQ_MODEL', default='llama-3.3-70b-versatile')

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Jazzmin Configuration (Simplified)
JAZZMIN_SETTINGS = {
    "site_title": "Infracontrol Admin",
    "site_header": "Infracontrol",
    "site_brand": "Infracontrol",
    "welcome_sign": "Bienvenue sur Infracontrol",
    "copyright": "Infracontrol",
}

# Verify Fernet Key
try:
    Fernet(FERNET_KEY)
    print("Clé Fernet valide")
except Exception as e:
    print(f"Clé Fernet invalide: {e}")