# Generated by Django 5.2.11 on 2026-03-13 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0030_equipementreseau_pos_x_equipementreseau_pos_y'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionformation',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='sessionformation',
            name='reussi',
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='description_scenario',
            field=models.TextField(blank=True, help_text="Briefing généré par l'IA au début de la session"),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='incident_source',
            field=models.ForeignKey(blank=True, help_text="L'incident historique utilisé comme scénario", null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.incident'),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En Cours'), ('termine_succes', 'Terminé (Succès)'), ('termine_echec', 'Terminé (Échec)')], default='en_cours', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='tentatives_cli',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='titre_scenario',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sessionformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_formation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MessageInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Stagiaire'), ('assistant', 'IA Système')], max_length=10)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='training.sessionformation')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.DeleteModel(
            name='ScenarioFormation',
        ),
    ]
